# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6928312675ecfc3f516842f43f6b71988ff801d16fd8c630148f3c5269bd672ca92c08f5500a96bea72b0589089d62265ce9212d5b4a00258ca5bb7536873406

test:
  secret_key_base: 0b1ba034056d0fa2dc5dd1d8d18fc3062f66336e026b0e68ceff15909afb2edd958965bbc79e5ec11aa7e8ccb0486dfb8f969316cb9bdb95b2941eff9794cbce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
